# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

variables:
  solutionPath: StoreApplication

jobs:
  - job: build_linux
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: dotnet build -c Release
      displayName: Build Project/Application and Release Config
      workingDirectory: $(solutionPath)

    - task: DotNetCoreCLI@2
      displayName: run project tests
      inputs:
        command: 'test'
        projects: '$(solutionPath)'
        arguments: '-c Release'
        testRunTitle: 'ubuntu'
